### ISSUE TITLE
subscribe button 

### ISSUE THREAD

**Issue by amitranjan0220** [safwanrahman/django-webpush#43]
latest version subscribe button do not shows

**Comment by amitranjan0220** [comment]
on  version 0.2.2.2 works fine button shows but using latest version 
it does not work

**Comment by safwanrahman** [comment]
Can you please provide more information?

**Comment by siddhantkhandelwal** [comment]
After following the directions as mentioned, I included the template tag {{ webpush_button }} in my template. But the button is not rendered. When I used inspect from chrome, a blank line replaces {{ webpush_button }}.

**Comment by safwanrahman** [comment]
can you please provide more information? what do you see in th console?

**Comment by Mogost** [comment]
Can confirm this issue.
After my investigation i found that problem is in `/webpush/templatetags/webpush_notifications.py`
get_templatetag_context returns 
```
    data = {'group': context.get('webpush', {}).get('group'),
            'user': getattr(request, 'user', None),
            'vapid_public_key': vapid_public_key,
            'webpush_save_url': reverse('save_webpush_info')
            }
```
in `django/template/library.py` generates new context with this dict `new_context = context.new(_dict)`.
template is 
```
{% if request.user.is_authenticated or group %}
  <button id="webpush-subscribe-button" {% if group %}data-group="{{ group }}"{% endif %} data-url="{{ webpush_save_url }}">
    Subscribe to Push Messaging
  </button>
  <div id="webpush-message" hidden></div>
{% endif %}
```
When rendering this template there is no `request`.
